import { describe, it, expect } from 'vitest';
import { csvCell, priceFile, priceParsed, toCsv, totals } from './batch';
import { defaultValues } from './profiles';

const gcode = (w: number, secs: string) =>
  new TextEncoder().encode(`; generated by PrusaSlicer 2.7.0\n; filament used [g] = ${w}\n; estimated printing time (normal mode) = ${secs}\nG1 X0\n`);

describe('pro batch', () => {
  it('prices a file and totals with quantity', async () => {
    const a = await priceFile('a.gcode', gcode(50, '2h 0m 0s'), defaultValues(), 3);
    const b = await priceFile('b.gcode', gcode(10, '30m 0s'), defaultValues());
    expect(a.error).toBeUndefined();
    expect(a.weightG).toBe(50);
    expect(a.printTimeHours).toBeCloseTo(2);
    const t = totals([a, b]);
    expect(t.count).toBe(4);
    expect(t.weightG).toBeCloseTo(160);
    expect(t.price).toBeCloseTo(a.cost!.suggestedPrice * 3 + b.cost!.suggestedPrice);
  });
  it('records failures without throwing', async () => {
    const r = await priceFile('bad.3mf', new Uint8Array([0x50, 0x4b, 1, 2, 3]), defaultValues());
    expect(r.error).toBeTruthy();
    expect(totals([r]).failed).toBe(1);
  });
  it('clamps quantity and warns on missing data', () => {
    const r = priceParsed('x', { slicer: 'unknown', filaments: [], warnings: [] }, defaultValues(), -5);
    expect(r.quantity).toBe(1);
    expect(r.warnings.length).toBe(2);
    expect(priceParsed('x', { slicer: 'unknown', filaments: [], warnings: [] }, defaultValues(), NaN).quantity).toBe(1);
  });
  it('neutralises CSV injection and quotes properly', () => {
    expect(csvCell('=HYPERLINK("x")')).toBe(`"'=HYPERLINK(""x"")"`);
    expect(csvCell('+1')).toBe("'+1");
    expect(csvCell('a,b')).toBe('"a,b"');
    expect(csvCell('line\nbreak')).toBe('line break');
    expect(csvCell(1.23456789)).toBe('1.2346');
  });
  it('emits BOM, CRLF, header and total row', async () => {
    const csv = toCsv([await priceFile('=evil.gcode', gcode(20, '1h 0m 0s'), defaultValues())]);
    expect(csv.startsWith('﻿File,Quantity')).toBe(true);
    const lines = csv.trim().split('\r\n');
    expect(lines.length).toBe(3);
    expect(lines[1].startsWith("'=evil.gcode")).toBe(true);
    expect(lines[2].startsWith('TOTAL,1,')).toBe(true);
  });
});
