// Smoke tests for the built page, free path and local-only Pro preview. Written by an AI agent (Claude).
// Fixtures are synthetic (same header shape as real slicer output) so no third-party files are committed.
import { test, expect, type Page } from '@playwright/test';

const gcode = (grams: number, time: string) => Buffer.from(
  `; generated by PrusaSlicer 2.9.0\nG1 X1\n; filament used [mm] = 4000\n; filament used [g] = ${grams}\n; estimated printing time (normal mode) = ${time}\n`);
const file = (name: string, buffer: Buffer) => ({ name, mimeType: 'text/plain', buffer });

function trackErrors(page: Page) {
  const errors: string[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('dialog', (d) => { errors.push('dialog: ' + d.message()); void d.dismiss(); });
  return errors;
}

test('free calculator reads a G-code file and prices it', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/');
  await page.setInputFiles('#file', file('benchy.gcode', gcode(12.08, '54m 11s')));
  await expect(page.locator('#file-status')).toContainText('prusa');
  await expect(page.locator('#f-weightG')).toHaveValue('12.1');
  await expect(page.locator('#f-mins')).toHaveValue('54');
  // Hand-checked with the default settings: (2.9027 + 0.25) / 0.635 = 4.96.
  await expect(page.locator('#price')).toHaveText('$ 4.96');
  await expect(page.locator('footer')).toContainText('Built and maintained by an AI agent (Claude), with human oversight.');
  expect(errors).toEqual([]);
});

/** One-entry stored zip, enough to look like a plain 3D-model 3MF. */
function modelOnly3mf(): Buffer {
  const name = Buffer.from('3D/3dmodel.model'), data = Buffer.from('<model/>');
  const lh = Buffer.alloc(30); lh.writeUInt32LE(0x04034b50, 0); lh.writeUInt32LE(data.length, 18); lh.writeUInt32LE(data.length, 22); lh.writeUInt16LE(name.length, 26);
  const ch = Buffer.alloc(46); ch.writeUInt32LE(0x02014b50, 0); ch.writeUInt32LE(data.length, 20); ch.writeUInt32LE(data.length, 24); ch.writeUInt16LE(name.length, 28);
  const cdOffset = 30 + name.length + data.length;
  const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(1, 8); end.writeUInt16LE(1, 10); end.writeUInt32LE(46 + name.length, 12); end.writeUInt32LE(cdOffset, 16);
  return Buffer.concat([lh, name, data, ch, name, end]);
}

test('an unsliced 3MF gets a plain explanation, not a generic error', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/');
  await page.setInputFiles('#file', { name: 'model.3mf', mimeType: 'application/octet-stream', buffer: modelOnly3mf() });
  await expect(page.locator('#file-status')).toHaveText(/^This is a 3D model, not a sliced file\..*Enter weight and time manually below\.$/);
  expect(errors).toEqual([]);
});

test('no sideways scroll on a 320px phone', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 });
  await page.goto('/');
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
});

test('Pro preview stays closed without ?pro', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('h1')).toBeVisible();
  await expect(page.locator('#pro-batch, #pro-profiles')).toHaveCount(0);
});

test('Pro preview: batch, CSV, hostile names, quote', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/?pro');
  await page.setInputFiles('#batch-files', [
    file('a.gcode', gcode(12.08, '54m 11s')),
    file('=HYPERLINK(x)<img src=x onerror=alert(1)>.gcode', gcode(6.64, '37m 15s')),
    { name: 'bad.3mf', mimeType: 'application/octet-stream', buffer: Buffer.from('PK\x03\x04junk') },
  ]);
  await expect(page.locator('#batch-status')).toContainText('3 file(s) in batch');
  await expect(page.locator('#batch-table img')).toHaveCount(0);
  await expect(page.locator('#batch-table tbody tr').nth(2)).toContainText('Could not read file');
  await expect(page.locator('#batch-table tbody tr').nth(0).locator('td').nth(4)).toHaveText('$ 4.96');

  const [download] = await Promise.all([page.waitForEvent('download'), page.click('#batch-csv')]);
  const csv = await (await download.createReadStream()).toArray().then((c) => Buffer.concat(c).toString('utf8'));
  expect(csv).toContain("'=HYPERLINK");
  expect(csv).toMatch(/\r\nTOTAL,2,/);

  await page.fill('#q-seller', 'Shop <b>x</b>');
  await page.click('#q-show');
  const quote = page.frameLocator('#q-frame');
  await expect(quote.locator('h1')).toHaveText('Quote');
  await expect(quote.locator('body')).toContainText('Shop <b>x</b>');
  await expect(quote.locator('b, img, script')).toHaveCount(0);
  expect(errors).toEqual([]);
});
