// Smoke tests for the built page, free path and local-only Pro preview. Written by an AI agent (Claude).
// Fixtures are synthetic (same header shape as real slicer output) so no third-party files are committed.
import { test, expect, type Page } from '@playwright/test';

const gcode = (grams: number, time: string) => Buffer.from(
  `; generated by PrusaSlicer 2.9.0\nG1 X1\n; filament used [mm] = 4000\n; filament used [g] = ${grams}\n; estimated printing time (normal mode) = ${time}\n`);
const file = (name: string, buffer: Buffer) => ({ name, mimeType: 'text/plain', buffer });

function trackErrors(page: Page) {
  const errors: string[] = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('dialog', (d) => { errors.push('dialog: ' + d.message()); void d.dismiss(); });
  return errors;
}

test('free calculator reads a G-code file and prices it', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/');
  await page.setInputFiles('#file', file('benchy.gcode', gcode(12.08, '54m 11s')));
  await expect(page.locator('#file-status')).toContainText('prusa');
  await expect(page.locator('#f-weightG')).toHaveValue('12.1');
  await expect(page.locator('#f-mins')).toHaveValue('54');
  // Hand-checked with the default settings: (2.9027 + 0.25) / 0.635 = 4.96.
  await expect(page.locator('#price')).toHaveText('$ 4.96');
  await expect(page.locator('footer')).toContainText('Built and maintained by an AI agent (Claude), with human oversight.');
  expect(errors).toEqual([]);
});

/** One-entry stored zip, enough to look like a plain 3D-model 3MF. */
function modelOnly3mf(): Buffer {
  const name = Buffer.from('3D/3dmodel.model'), data = Buffer.from('<model/>');
  const lh = Buffer.alloc(30); lh.writeUInt32LE(0x04034b50, 0); lh.writeUInt32LE(data.length, 18); lh.writeUInt32LE(data.length, 22); lh.writeUInt16LE(name.length, 26);
  const ch = Buffer.alloc(46); ch.writeUInt32LE(0x02014b50, 0); ch.writeUInt32LE(data.length, 20); ch.writeUInt32LE(data.length, 24); ch.writeUInt16LE(name.length, 28);
  const cdOffset = 30 + name.length + data.length;
  const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(1, 8); end.writeUInt16LE(1, 10); end.writeUInt32LE(46 + name.length, 12); end.writeUInt32LE(cdOffset, 16);
  return Buffer.concat([lh, name, data, ch, name, end]);
}

test('an unsliced 3MF gets a plain explanation, not a generic error', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/');
  await page.setInputFiles('#file', { name: 'model.3mf', mimeType: 'application/octet-stream', buffer: modelOnly3mf() });
  await expect(page.locator('#file-status')).toHaveText(/^This is a 3D model, not a sliced file\..*Enter weight and time manually below\.$/);
  expect(errors).toEqual([]);
});

test('no sideways scroll on a 320px phone', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 });
  await page.goto('/');
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
});

test('Pro preview stays closed without ?pro', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('h1')).toBeVisible();
  await expect(page.locator('#pro-batch, #pro-profiles')).toHaveCount(0);
});

test('Pro preview: batch, CSV, hostile names, quote', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/?pro');
  await page.setInputFiles('#batch-files', [
    file('a.gcode', gcode(12.08, '54m 11s')),
    file('=HYPERLINK(x)<img src=x onerror=alert(1)>.gcode', gcode(6.64, '37m 15s')),
    { name: 'bad.3mf', mimeType: 'application/octet-stream', buffer: Buffer.from('PK\x03\x04junk') },
  ]);
  await expect(page.locator('#batch-status')).toContainText('3 file(s) in batch');
  await expect(page.locator('#batch-table img')).toHaveCount(0);
  await expect(page.locator('#batch-table tbody tr').nth(2)).toContainText('Could not read file');
  await expect(page.locator('#batch-table tbody tr').nth(0).locator('td').nth(4)).toHaveText('$ 4.96');

  const [download] = await Promise.all([page.waitForEvent('download'), page.click('#batch-csv')]);
  const csv = await (await download.createReadStream()).toArray().then((c) => Buffer.concat(c).toString('utf8'));
  expect(csv).toContain("'=HYPERLINK");
  expect(csv).toMatch(/\r\nTOTAL,2,/);

  await page.fill('#q-seller', 'Shop <b>x</b>');
  await page.click('#q-show');
  const quote = page.frameLocator('#q-frame');
  await expect(quote.locator('h1')).toHaveText('Quote');
  await expect(quote.locator('body')).toContainText('Shop <b>x</b>');
  await expect(quote.locator('b, img, script')).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('Pro preview: printer, material and shop libraries', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/?pro');
  await page.fill('#f-filamentPricePerKg', '30');
  await page.fill('#p-material-name', 'PETG <img src=x onerror=alert(1)>');
  await page.click('#p-material-save');
  await expect(page.locator('#pro-profiles [role=status]')).toContainText('Saved material');
  await page.fill('#f-printerPowerW', '150');
  await page.fill('#p-printer-name', 'P1S');
  await page.click('#p-printer-save');

  // Picking the material restores only material fields.
  await page.fill('#f-filamentPricePerKg', '15');
  await page.selectOption('#p-material', '');
  await page.selectOption('#p-material', { index: 1 });
  await expect(page.locator('#f-filamentPricePerKg')).toHaveValue('30');
  await expect(page.locator('#f-printerPowerW')).toHaveValue('150');
  await expect(page.locator('#pro-profiles img')).toHaveCount(0);

  // Selection and library survive a reload.
  await page.reload();
  await expect(page.locator('#p-material option:checked')).toHaveText('PETG <img src=x onerror=alert(1)>');
  await expect(page.locator('#p-printer option')).toHaveText(['Choose a printer…', 'P1S']);

  // A file whose filament type matches a saved material preselects it.
  await page.fill('#f-filamentPricePerKg', '15');
  const petg = Buffer.from('; generated by PrusaSlicer 2.9.0\n; filament used [g] = 20\n; filament_type = PETG\n; estimated printing time (normal mode) = 1h\n');
  await page.setInputFiles('#file', { name: 'petg.gcode', mimeType: 'text/plain', buffer: petg });
  await expect(page.locator('#pro-profiles [role=status]')).toContainText('Matched material');
  await expect(page.locator('#f-filamentPricePerKg')).toHaveValue('30');

  // Two filaments, two saved materials: weight-weighted blend (10 g at 30 + 30 g at 10, no waste) = 15.
  await page.fill('#f-filamentPricePerKg', '10');
  await page.fill('#f-wastePct', '0');
  await page.fill('#p-material-name', 'Basic PLA');
  await page.click('#p-material-save');
  await page.fill('#f-filamentPricePerKg', '30');
  await page.fill('#p-material-name', 'PETG <img src=x onerror=alert(1)>');
  await page.click('#p-material-save');
  const mixed = Buffer.from('; generated by PrusaSlicer 2.9.0\n; filament used [g] = 10.00, 30.00\n; filament_type = PETG;PLA\n; estimated printing time (normal mode) = 2h\n');
  await page.setInputFiles('#file', { name: 'mixed.gcode', mimeType: 'text/plain', buffer: mixed });
  await expect(page.locator('#pro-profiles [role=status]')).toContainText('Matched 2 materials');
  await expect(page.locator('#f-filamentPricePerKg')).toHaveValue('15');
  await expect(page.locator('#f-wastePct')).toHaveValue('0');
  await expect(page.locator('#pro-profiles img')).toHaveCount(0);

  // A v1 flat-profile file is split into all three libraries; a bad file changes nothing.
  const v1 = JSON.stringify({ format: 'smallhours-profiles', version: 1, profiles: [{ name: 'Old', values: { feePct: 6.5 } }] });
  await page.setInputFiles('#p-import', { name: 'old.json', mimeType: 'application/json', buffer: Buffer.from(v1) });
  await expect(page.locator('#pro-profiles [role=status]')).toContainText('Imported 3 entries');
  await expect(page.locator('#p-shop option')).toHaveText(['Choose a shop…', 'Old']);
  const bad = JSON.stringify({ format: 'smallhours-profiles', version: 2, shops: [{ name: 'X', values: { feePct: -5 } }] });
  await page.setInputFiles('#p-import', { name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from(bad) });
  await expect(page.locator('#pro-profiles [role=status]')).toContainText('Nothing was changed');
  await expect(page.locator('#p-shop option')).toHaveCount(2);
  expect(errors).toEqual([]);
});

test('Pro preview: a file naming the printer preselects the saved printer (hq t012)', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/?pro');
  for (const [name, w] of [['MK4S', '80'], ['Bambu Lab P1S', '150']]) {
    await page.fill('#f-printerPowerW', w);
    await page.fill('#p-printer-name', name);
    await page.click('#p-printer-save');
  }
  await page.fill('#f-printerPowerW', '100');
  const mk4s = Buffer.from('; generated by PrusaSlicer 2.9.0\n; filament used [g] = 20\n; estimated printing time (normal mode) = 1h\n; printer_model = MK4S\n; printer_settings_id = Original Prusa MK4S 0.4 nozzle\n');
  await page.setInputFiles('#file', { name: 'mk4s.gcode', mimeType: 'text/plain', buffer: mk4s });
  await expect(page.locator('#p-printer-matched')).toHaveText('Matched printer "MK4S" (file says "MK4S"). Pick another if that\'s wrong.');
  await expect(page.locator('#p-printer option:checked')).toHaveText('MK4S');
  await expect(page.locator('#f-printerPowerW')).toHaveValue('80');
  await expect(page.locator('#file-status')).toContainText('printer: MK4S');

  // Hostile printer text stays text; an unknown printer clears the note and leaves the choice alone.
  const evil = Buffer.from('; generated by OrcaSlicer 2.3.1\n; total filament weight [g] : 5\n; total estimated time: 1h\n; printer_model = <img src=x onerror=alert(1)>\n');
  await page.setInputFiles('#file', { name: 'evil.gcode', mimeType: 'text/plain', buffer: evil });
  await expect(page.locator('#file-status')).toContainText('printer: <img src=x onerror=alert(1)>');
  await expect(page.locator('#p-printer-matched')).toHaveText('');
  await expect(page.locator('#p-printer option:checked')).toHaveText('MK4S');
  await expect(page.locator('img')).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('free page offers the sourced power for the file\'s printer, only on click (hq t013)', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/');
  await page.fill('#f-printerPowerW', '100');
  const p1s = Buffer.from('; generated by OrcaSlicer 2.3.1\n; total filament weight [g] : 5\n; total estimated time: 1h\n; printer_model = Bambu Lab P1S\n');
  await page.setInputFiles('#file', { name: 'p1s.gcode', mimeType: 'text/plain', buffer: p1s });
  await expect(page.locator('#power-hint')).toBeVisible();
  await expect(page.locator('#power-hint-text')).toContainText('Bambu Lab P1S, which averages about 105 W');
  await expect(page.locator('#f-printerPowerW')).toHaveValue('100');
  await page.click('#power-hint-use');
  await expect(page.locator('#f-printerPowerW')).toHaveValue('105');
  await expect(page.locator('#power-hint')).toBeHidden();

  // Same printer again: setting already matches, so no note. Unknown printer or no printer: no note.
  await page.setInputFiles('#file', { name: 'p1s.gcode', mimeType: 'text/plain', buffer: p1s });
  await expect(page.locator('#file-status')).toContainText('printer: Bambu Lab P1S');
  await expect(page.locator('#power-hint')).toBeHidden();
  await page.fill('#f-printerPowerW', '100');
  await page.setInputFiles('#file', file('benchy.gcode', gcode(12.08, '54m 11s')));
  await expect(page.locator('#file-status')).toContainText('Detected slicer');
  await expect(page.locator('#power-hint')).toBeHidden();
  expect(errors).toEqual([]);
});

test('pricing guide links open the calculator with the example job (hq t016)', async ({ page }) => {
  const errors = trackErrors(page);
  await page.goto('/guides/how-to-price-3d-prints/');
  await page.getByRole('link', { name: 'Open this example in the calculator' }).click();
  await expect(page.locator('#f-weightG')).toHaveValue('62.1');
  await expect(page.locator('#f-hours')).toHaveValue('7');
  await expect(page.locator('#f-mins')).toHaveValue('25');
  // Same as the guide's table with the default settings.
  await expect(page.locator('#price')).toHaveText('$ 8.31');
  // Cost settings never come from the URL.
  await page.goto('/#g=10&feePct=90');
  await expect(page.locator('#f-feePct')).toHaveValue('6.5');
  expect(errors).toEqual([]);
});
