import type { ParsedFile } from './types';
import { ParseError } from './types';
import { parseGcodeText } from './gcode';
import { inflate } from './zip';

// Prusa binary G-code (.bgcode), spec: https://github.com/prusa3d/libbgcode
// File header: "GCDE", version u32, checksum type u16. Then blocks:
// type u16, compression u16, uncompressed size u32, [compressed size u32 if compressed],
// params (6 bytes for thumbnails, 2 otherwise), data, [CRC32 if checksum type is 1].
const BLOCK_GCODE = 1;
const BLOCK_THUMBNAIL = 5;
const METADATA_BLOCKS = new Set([0, 2, 3, 4]); // file, slicer, printer, print
const COMPRESSION_NONE = 0;
const COMPRESSION_DEFLATE = 1;
const MAX_METADATA_BYTES = 4 * 1024 * 1024;

export function isBgcode(bytes: Uint8Array): boolean {
  return bytes.length >= 10 && bytes[0] === 0x47 && bytes[1] === 0x43 && bytes[2] === 0x44 && bytes[3] === 0x45;
}

/** Read the metadata blocks (they precede the G-code blocks) and parse them like a G-code footer. */
export async function parseBgcode(bytes: Uint8Array): Promise<ParsedFile> {
  const d = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const checksumBytes = d.getUint16(8, true) === 1 ? 4 : 0;
  const dec = new TextDecoder();
  const lines: string[] = [];
  let producer = '';
  let o = 10;
  while (o + 8 <= bytes.length) {
    const type = d.getUint16(o, true);
    const compression = d.getUint16(o + 2, true);
    const usize = d.getUint32(o + 4, true);
    o += 8;
    let size = usize;
    if (compression !== COMPRESSION_NONE) {
      if (o + 4 > bytes.length) break;
      size = d.getUint32(o, true);
      o += 4;
    }
    if (type === BLOCK_GCODE) break;
    o += type === BLOCK_THUMBNAIL ? 6 : 2;
    if (o + size > bytes.length) throw new ParseError('Corrupt .bgcode file');
    if (METADATA_BLOCKS.has(type)) {
      if (usize > MAX_METADATA_BYTES) throw new ParseError('Corrupt .bgcode file');
      const raw = bytes.subarray(o, o + size);
      let data: Uint8Array | undefined;
      if (compression === COMPRESSION_NONE) data = raw;
      else if (compression === COMPRESSION_DEFLATE) data = await inflate(raw, usize + 1024, 'deflate');
      if (data) {
        for (const l of dec.decode(data).split(/\r?\n/)) {
          if (!l.includes('=')) continue;
          if (type === 0 && l.startsWith('Producer=')) producer = l.slice(9);
          lines.push('; ' + l.replace('=', ' = '));
        }
      }
    }
    o += size + checksumBytes;
  }
  if (producer) lines.unshift('; generated by ' + producer);
  return parseGcodeText(lines.join('\n'));
}
