import type { FilamentUsage, ParsedFile, Slicer } from './types';
import { cleanLabel } from './types';
import { parseDuration } from './time';

const DEFAULT_DIAMETER_MM = 1.75;
const DEFAULT_DENSITY_G_CM3 = 1.24; // PLA
// Typical densities (g/cm3) used as slicer defaults; only for files whose profile has no usable density.
const TYPE_DENSITY: Record<string, number> = { PLA: 1.24, PETG: 1.27, ABS: 1.04, ASA: 1.07, TPU: 1.21, PC: 1.2, PA: 1.14, NYLON: 1.14 };
const typeDensity = (t?: string) => (t ? TYPE_DENSITY[t.toUpperCase().split(/[-\s]/)[0]] : undefined);

function numberList(s: string): number[] {
  return s
    .split(/[,;]/)
    .map((x) => parseFloat(x.trim()))
    .filter((n) => Number.isFinite(n));
}

function weightFromLength(lengthMm: number, diameterMm: number, density: number): number {
  const r = diameterMm / 2;
  return (Math.PI * r * r * lengthMm * density) / 1000; // mm^3 -> cm^3 = /1000
}

/** Look at a G-code header/footer text and extract slicer-reported totals. */
export function parseGcodeText(text: string): ParsedFile {
  const warnings: string[] = [];
  // Slicers put metadata at the top (Cura, Bambu) and/or bottom (Prusa, Orca). Scan both ends.
  const MAX = 300_000;
  const scan = text.length > 2 * MAX ? text.slice(0, MAX) + '\n' + text.slice(-MAX) : text;
  const lines = scan.split(/\r?\n/).filter((l) => l.startsWith(';'));
  const kv = (re: RegExp): string | undefined => {
    for (let i = lines.length - 1; i >= 0; i--) {
      const m = re.exec(lines[i]);
      if (m) return m[1];
    }
    return undefined;
  };

  let slicer: Slicer = 'unknown';
  const gen = lines.find((l) => /^;\s*generated by|^;\s*BambuStudio|^;\s*Sliced by|^;FLAVOR:|^;Generated with Cura/i.test(l)) ?? '';
  if (/BambuStudio|Bambu Studio/i.test(scan.slice(0, 5000))) slicer = 'bambu';
  else if (/OrcaSlicer/i.test(gen) || /OrcaSlicer/i.test(scan.slice(0, 5000))) slicer = 'orca';
  else if (/PrusaSlicer|SuperSlicer/i.test(gen)) slicer = 'prusa';
  else if (/Cura|^;FLAVOR:/i.test(gen) || kv(/^;TIME:(\d+)/) !== undefined) slicer = 'cura';

  let printTimeSeconds: number | undefined;
  const filaments: FilamentUsage[] = [];

  // --- Cura ---
  const curaTime = kv(/^;TIME:\s*(\d+)/);
  if (curaTime !== undefined) printTimeSeconds = parseInt(curaTime, 10);
  const curaUsed = kv(/^;Filament used:\s*(.+)$/i);
  if (curaUsed !== undefined) {
    // "1.23m" or "1.2m, 0.5m"
    for (const part of curaUsed.split(',')) {
      const m = /([\d.]+)\s*(mm|m)\b/.exec(part.trim());
      if (m) filaments.push({ lengthMm: parseFloat(m[1]) * (m[2] === 'm' ? 1000 : 1) });
    }
  }

  // --- Cura "Griffin" header (UltiMaker printers): time in seconds, filament as volume in mm^3 ---
  const griffinTime = kv(/^;PRINT\.TIME:\s*(\d+)/);
  if (printTimeSeconds === undefined && griffinTime !== undefined) printTimeSeconds = parseInt(griffinTime, 10);
  const griffinVolumes: number[] = [];
  for (const l of lines) {
    const m = /^;EXTRUDER_TRAIN\.(\d+)\.MATERIAL\.VOLUME_USED:\s*([\d.]+)/.exec(l);
    if (m) griffinVolumes[parseInt(m[1], 10)] = parseFloat(m[2]);
  }
  if (filaments.length === 0) {
    for (const v of griffinVolumes) {
      if (v > 0) filaments.push({ weightG: (v / 1000) * DEFAULT_DENSITY_G_CM3, weightEstimated: true });
    }
  }

  // --- Prusa / Orca / Bambu ---
  const gList = kv(/^;\s*filament used \[g\]\s*[=:]\s*(.+)$/i);
  const mmList = kv(/^;\s*filament used \[mm\]\s*[=:]\s*(.+)$/i);
  const typeList = kv(/^;\s*filament_type\s*=\s*(.+)$/i);
  const diaList = kv(/^;\s*filament_diameter\s*=\s*(.+)$/i);
  const densList = kv(/^;\s*filament_density\s*=\s*(.+)$/i);
  const cm3List = kv(/^;\s*filament used \[cm3\]\s*[=:]\s*(.+)$/i);
  if (gList !== undefined || mmList !== undefined) {
    filaments.length = 0;
    const g = gList ? numberList(gList) : [];
    const mm = mmList ? numberList(mmList) : [];
    const cm3 = cm3List ? numberList(cm3List) : [];
    const types = typeList ? typeList.split(/[;,]/).map((t) => t.trim()) : [];
    const n = Math.max(g.length, mm.length);
    for (let i = 0; i < n; i++) {
      const f: FilamentUsage = {};
      if (g[i] !== undefined) f.weightG = g[i];
      if (mm[i] !== undefined) f.lengthMm = mm[i];
      if (cm3[i] !== undefined && cm3[i] > 0) f.volumeCm3 = cm3[i];
      if (types[i]) f.type = types[i];
      filaments.push(f);
    }
    // Drop unused (zero) extruders in multi-material files, but keep at least one entry.
    if (filaments.length > 1) {
      const used = filaments.filter((f) => (f.weightG ?? f.lengthMm ?? 0) > 0);
      if (used.length) filaments.splice(0, filaments.length, ...used);
    }
  }
  const total = kv(/^;\s*total filament weight \[g\]\s*[:=]\s*([\d.]+)/i);
  if (total !== undefined && !filaments.some((f) => f.weightG !== undefined)) {
    filaments.push({ weightG: parseFloat(total) });
  }

  if (printTimeSeconds === undefined) {
    const est =
      kv(/^;\s*estimated printing time \(normal mode\)\s*=\s*(.+)$/i) ??
      kv(/^;\s*total estimated time:\s*(.+?)(?:;|$)/i) ??
      kv(/^;\s*estimated printing time[^=:]*[=:]\s*(.+)$/i);
    if (est) printTimeSeconds = parseDuration(est);
  }

  // Derive weight when the file has none. A reported 0 g with filament used means the profile had no density
  // (e.g. OrcaSlicer with filament_density = 0), so treat it as missing too.
  const dia = diaList ? numberList(diaList) : [];
  const dens = densList ? numberList(densList) : [];
  let noDensity = false;
  filaments.forEach((f, i) => {
    const used = (f.lengthMm ?? 0) > 0 || (f.volumeCm3 ?? 0) > 0;
    if (f.weightG === 0 && used) delete f.weightG;
    if (f.weightG !== undefined || !used) return;
    const fileDensity = dens[i] ?? dens[0];
    if (fileDensity !== undefined && !(fileDensity > 0)) noDensity = true;
    const density = fileDensity !== undefined && fileDensity > 0 ? fileDensity : typeDensity(f.type) ?? DEFAULT_DENSITY_G_CM3;
    f.weightG = f.volumeCm3 !== undefined
      ? f.volumeCm3 * density
      : weightFromLength(f.lengthMm!, dia[i] ?? dia[0] ?? DEFAULT_DIAMETER_MM, density);
    f.weightEstimated = true;
  });
  filaments.forEach((f) => delete f.volumeCm3);
  if (noDensity) warnings.push('Your slicer profile has no filament density, so weight is estimated.');
  if (filaments.some((f) => f.weightEstimated)) {
    warnings.push('Weight was estimated from filament length or volume (assumes 1.75 mm, PLA density unless the file says otherwise). Check it against your slicer.');
  }
  if (filaments.length === 0) warnings.push('No filament usage found in this file. Enter it manually.');
  if (printTimeSeconds === undefined) warnings.push('No print time found in this file. Enter it manually.');

  // Printer: Prusa/Orca/Bambu config lines (Orca also writes ";printer_model:..."), Cura Griffin header.
  const printerModel = cleanLabel(kv(/^;\s*printer_model\s*[=:]\s*(.+)$/) ?? kv(/^;TARGET_MACHINE\.NAME:\s*(.+)$/));
  const printerPreset = cleanLabel(kv(/^;\s*printer_settings_id\s*=\s*(.+)$/));

  return { slicer, printTimeSeconds, filaments, totalWeightG: sumWeights(filaments), printerModel, printerPreset, warnings };
}

export function sumWeights(filaments: FilamentUsage[]): number | undefined {
  const w = filaments.map((f) => f.weightG).filter((x): x is number => x !== undefined);
  return w.length ? Math.round(w.reduce((a, b) => a + b, 0) * 100) / 100 : undefined;
}
