import { describe, expect, it } from 'vitest';
import { deflateRawSync } from 'node:zlib';
import { parseFile } from './parsers/index';
import { parseGcodeText } from './parsers/gcode';
import { parseDuration } from './parsers/time';

function makeZip(files: Record<string, string>, stored = false): Uint8Array {
  const parts: Buffer[] = [];
  const central: Buffer[] = [];
  let offset = 0;
  for (const [name, content] of Object.entries(files)) {
    const raw = Buffer.from(content);
    const data = stored ? raw : deflateRawSync(raw);
    const nb = Buffer.from(name);
    const lh = Buffer.alloc(30);
    lh.writeUInt32LE(0x04034b50, 0);
    lh.writeUInt16LE(20, 4);
    lh.writeUInt16LE(stored ? 0 : 8, 8);
    lh.writeUInt32LE(data.length, 18);
    lh.writeUInt32LE(raw.length, 22);
    lh.writeUInt16LE(nb.length, 26);
    parts.push(lh, nb, data);
    const ch = Buffer.alloc(46);
    ch.writeUInt32LE(0x02014b50, 0);
    ch.writeUInt16LE(20, 4);
    ch.writeUInt16LE(20, 6);
    ch.writeUInt16LE(stored ? 0 : 8, 10);
    ch.writeUInt32LE(data.length, 20);
    ch.writeUInt32LE(raw.length, 24);
    ch.writeUInt16LE(nb.length, 28);
    ch.writeUInt32LE(offset, 42);
    central.push(ch, nb);
    offset += 30 + nb.length + data.length;
  }
  const cd = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(Object.keys(files).length, 8);
  end.writeUInt16LE(Object.keys(files).length, 10);
  end.writeUInt32LE(cd.length, 12);
  end.writeUInt32LE(offset, 16);
  return new Uint8Array(Buffer.concat([...parts, cd, end]));
}

describe('parseDuration', () => {
  it('parses d/h/m/s', () => {
    expect(parseDuration('1d 2h 3m 4s')).toBe(86400 + 7200 + 180 + 4);
    expect(parseDuration('45m 10s')).toBe(2710);
    expect(parseDuration('nothing')).toBeUndefined();
  });
});

describe('gcode', () => {
  it('PrusaSlicer footer, multi-filament', () => {
    const t = `; generated by PrusaSlicer 2.8.0\nG1 X1\n; filament used [mm] = 1000.5, 0.00, 250.0\n; filament used [g] = 3.01, 0.00, 0.75\n; filament_type = PLA;PETG;PLA\n; estimated printing time (normal mode) = 1h 20m 5s\n`;
    const r = parseGcodeText(t);
    expect(r.slicer).toBe('prusa');
    expect(r.printTimeSeconds).toBe(4805);
    expect(r.filaments).toHaveLength(2);
    expect(r.totalWeightG).toBe(3.76);
    expect(r.filaments[0].type).toBe('PLA');
  });
  it('Cura header, derives weight from length', () => {
    const r = parseGcodeText(';FLAVOR:Marlin\n;TIME:3600\n;Filament used: 2.5m\n;Generated with Cura_SteamEngine 5.7\nG1 X1\n');
    expect(r.slicer).toBe('cura');
    expect(r.printTimeSeconds).toBe(3600);
    expect(r.filaments[0].weightEstimated).toBe(true);
    expect(r.totalWeightG).toBeCloseTo(7.456, 2);
    expect(r.warnings.length).toBe(1);
  });
  it('Orca footer', () => {
    const t = `; generated by OrcaSlicer 2.1.0\n; total filament weight [g] : 12.34\n; total estimated time: 2h 3m 4s\n`;
    const r = parseGcodeText(t);
    expect(r.slicer).toBe('orca');
    expect(r.totalWeightG).toBe(12.34);
    expect(r.printTimeSeconds).toBe(7384);
  });
  it('falls back gracefully on unknown input', () => {
    const r = parseGcodeText('G1 X1 Y1\nG1 X2\n');
    expect(r.slicer).toBe('unknown');
    expect(r.filaments).toEqual([]);
    expect(r.totalWeightG).toBeUndefined();
    expect(r.warnings).toHaveLength(2);
  });
});

describe('3mf', () => {
  const sliceInfo = `<?xml version="1.0"?><config><plate><metadata key="index" value="1"/><metadata key="prediction" value="5400"/><metadata key="weight" value="20.5"/><filament id="1" type="PLA" color="#fff" used_m="5.2" used_g="15.5"/><filament id="2" type="PETG" used_m="1.9" used_g="5.0"/></plate></config>`;
  it('reads Bambu slice_info.config (deflate)', async () => {
    const r = await parseFile(makeZip({ 'Metadata/slice_info.config': sliceInfo, '3D/3dmodel.model': '<model/>' }));
    expect(r.slicer).toBe('bambu');
    expect(r.printTimeSeconds).toBe(5400);
    expect(r.filaments.map((f) => f.type)).toEqual(['PLA', 'PETG']);
    expect(r.totalWeightG).toBe(20.5);
  });
  it('reads stored entries', async () => {
    const r = await parseFile(makeZip({ 'Metadata/slice_info.config': sliceInfo }, true));
    expect(r.totalWeightG).toBe(20.5);
  });
  it('falls back to plate gcode', async () => {
    const r = await parseFile(makeZip({ 'Metadata/plate_1.gcode': '; BambuStudio 01.09\n; filament used [g] = 9.5\n; total estimated time: 30m 0s\n' }));
    expect(r.totalWeightG).toBe(9.5);
    expect(r.printTimeSeconds).toBe(1800);
  });
  it('errors clearly on an unsliced 3MF', async () => {
    await expect(parseFile(makeZip({ '3D/3dmodel.model': '<model/>' }))).rejects.toThrow(/no print metadata/);
  });
  it('rejects corrupt zips', async () => {
    await expect(parseFile(new Uint8Array([0x50, 0x4b, 1, 2, 3, 4]))).rejects.toThrow();
  });
});
