import { describe, expect, it } from 'vitest';
import { deflateRawSync, deflateSync } from 'node:zlib';
import { parseFile, ParseError } from './parsers/index';
import { parseGcodeText } from './parsers/gcode';
import { parseDuration } from './parsers/time';

/** Builds a zip; zip64 mimics OrcaSlicer's writer (sizes/offsets in a zip64 extra field, zip64 end record). */
function makeZip(files: Record<string, string>, stored = false, zip64 = false): Uint8Array {
  const parts: Buffer[] = [];
  const central: Buffer[] = [];
  let offset = 0;
  for (const [name, content] of Object.entries(files)) {
    const raw = Buffer.from(content);
    const data = stored ? raw : deflateRawSync(raw);
    const nb = Buffer.from(name);
    const lh = Buffer.alloc(30);
    lh.writeUInt32LE(0x04034b50, 0);
    lh.writeUInt16LE(20, 4);
    lh.writeUInt16LE(stored ? 0 : 8, 8);
    lh.writeUInt32LE(data.length, 18);
    lh.writeUInt32LE(raw.length, 22);
    lh.writeUInt16LE(nb.length, 26);
    parts.push(lh, nb, data);
    const ch = Buffer.alloc(46);
    ch.writeUInt32LE(0x02014b50, 0);
    ch.writeUInt16LE(20, 4);
    ch.writeUInt16LE(20, 6);
    ch.writeUInt16LE(stored ? 0 : 8, 10);
    ch.writeUInt32LE(zip64 ? 0xffffffff : data.length, 20);
    ch.writeUInt32LE(zip64 ? 0xffffffff : raw.length, 24);
    ch.writeUInt16LE(nb.length, 28);
    ch.writeUInt32LE(zip64 ? 0xffffffff : offset, 42);
    const extra = Buffer.alloc(zip64 ? 28 : 0);
    if (zip64) {
      ch.writeUInt16LE(28, 30);
      extra.writeUInt16LE(1, 0);
      extra.writeUInt16LE(24, 2);
      extra.writeBigUInt64LE(BigInt(raw.length), 4);
      extra.writeBigUInt64LE(BigInt(data.length), 12);
      extra.writeBigUInt64LE(BigInt(offset), 20);
    }
    central.push(ch, nb, extra);
    offset += 30 + nb.length + data.length;
  }
  const cd = Buffer.concat(central);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(Object.keys(files).length, 8);
  end.writeUInt16LE(Object.keys(files).length, 10);
  end.writeUInt32LE(cd.length, 12);
  end.writeUInt32LE(offset, 16);
  if (!zip64) return new Uint8Array(Buffer.concat([...parts, cd, end]));
  const n = BigInt(Object.keys(files).length);
  const z = Buffer.alloc(56);
  z.writeUInt32LE(0x06064b50, 0);
  z.writeBigUInt64LE(44n, 4);
  z.writeBigUInt64LE(n, 24);
  z.writeBigUInt64LE(n, 32);
  z.writeBigUInt64LE(BigInt(cd.length), 40);
  z.writeBigUInt64LE(BigInt(offset), 48);
  const loc = Buffer.alloc(20);
  loc.writeUInt32LE(0x07064b50, 0);
  loc.writeBigUInt64LE(BigInt(offset + cd.length), 8);
  loc.writeUInt32LE(1, 16);
  end.writeUInt16LE(0xffff, 8);
  end.writeUInt16LE(0xffff, 10);
  end.writeUInt32LE(0xffffffff, 16);
  return new Uint8Array(Buffer.concat([...parts, cd, z, loc, end]));
}

describe('parseDuration', () => {
  it('parses d/h/m/s', () => {
    expect(parseDuration('1d 2h 3m 4s')).toBe(86400 + 7200 + 180 + 4);
    expect(parseDuration('45m 10s')).toBe(2710);
    expect(parseDuration('nothing')).toBeUndefined();
  });
});

describe('gcode', () => {
  it('PrusaSlicer footer, multi-filament', () => {
    const t = `; generated by PrusaSlicer 2.8.0\nG1 X1\n; filament used [mm] = 1000.5, 0.00, 250.0\n; filament used [g] = 3.01, 0.00, 0.75\n; filament_type = PLA;PETG;PLA\n; estimated printing time (normal mode) = 1h 20m 5s\n`;
    const r = parseGcodeText(t);
    expect(r.slicer).toBe('prusa');
    expect(r.printTimeSeconds).toBe(4805);
    expect(r.filaments).toHaveLength(2);
    expect(r.totalWeightG).toBe(3.76);
    expect(r.filaments[0].type).toBe('PLA');
  });
  it('Cura header, derives weight from length', () => {
    const r = parseGcodeText(';FLAVOR:Marlin\n;TIME:3600\n;Filament used: 2.5m\n;Generated with Cura_SteamEngine 5.7\nG1 X1\n');
    expect(r.slicer).toBe('cura');
    expect(r.printTimeSeconds).toBe(3600);
    expect(r.filaments[0].weightEstimated).toBe(true);
    expect(r.totalWeightG).toBeCloseTo(7.456, 2);
    expect(r.warnings.length).toBe(1);
  });
  it('Orca footer', () => {
    const t = `; generated by OrcaSlicer 2.1.0\n; total filament weight [g] : 12.34\n; total estimated time: 2h 3m 4s\n`;
    const r = parseGcodeText(t);
    expect(r.slicer).toBe('orca');
    expect(r.totalWeightG).toBe(12.34);
    expect(r.printTimeSeconds).toBe(7384);
  });
  it('Cura Griffin header (UltiMaker), volume per extruder', () => {
    // Header shape from real Cura 4.6 output for an UltiMaker S5.
    const t = ';START_OF_HEADER\n;FLAVOR:Griffin\n;GENERATOR.NAME:Cura_SteamEngine\n;EXTRUDER_TRAIN.0.MATERIAL.VOLUME_USED:325509\n;EXTRUDER_TRAIN.1.MATERIAL.VOLUME_USED:35500\n;PRINT.TIME:353667\n;END_OF_HEADER\n;Generated with Cura_SteamEngine 4.6.2\nG1 X1\n';
    const r = parseGcodeText(t);
    expect(r.slicer).toBe('cura');
    expect(r.printTimeSeconds).toBe(353667);
    expect(r.filaments).toHaveLength(2);
    expect(r.filaments[0].weightEstimated).toBe(true);
    expect(r.totalWeightG).toBeCloseTo((325.509 + 35.5) * 1.24, 1);
  });
  it('falls back gracefully on unknown input', () => {
    const r = parseGcodeText('G1 X1 Y1\nG1 X2\n');
    expect(r.slicer).toBe('unknown');
    expect(r.filaments).toEqual([]);
    expect(r.totalWeightG).toBeUndefined();
    expect(r.warnings).toHaveLength(2);
  });
});

describe('3mf', () => {
  const sliceInfo = `<?xml version="1.0"?><config><plate><metadata key="index" value="1"/><metadata key="prediction" value="5400"/><metadata key="weight" value="20.5"/><filament id="1" type="PLA" color="#fff" used_m="5.2" used_g="15.5"/><filament id="2" type="PETG" used_m="1.9" used_g="5.0"/></plate></config>`;
  it('reads Bambu slice_info.config (deflate)', async () => {
    const r = await parseFile(makeZip({ 'Metadata/slice_info.config': sliceInfo, '3D/3dmodel.model': '<model/>' }));
    expect(r.slicer).toBe('bambu');
    expect(r.printTimeSeconds).toBe(5400);
    expect(r.filaments.map((f) => f.type)).toEqual(['PLA', 'PETG']);
    expect(r.totalWeightG).toBe(20.5);
  });
  it('totals time and filament across plates', async () => {
    // Shape of a real Bambu Studio 02.08 two-plate export.
    const xml = `<config><plate><metadata key="index" value="1"/><metadata key="prediction" value="4817"/><filament id="1" type="PLA" used_m="25.73" used_g="77.98"/></plate><plate><metadata key="index" value="2"/><metadata key="prediction" value="4478"/><filament id="1" type="PLA" used_m="23.72" used_g="71.87"/></plate></config>`;
    const r = await parseFile(makeZip({ 'Metadata/slice_info.config': xml }));
    expect(r.printTimeSeconds).toBe(9295);
    expect(r.totalWeightG).toBe(149.85);
    expect(r.warnings.join(' ')).toMatch(/2 sliced plates/);
  });
  it('reads zip64 archives (OrcaSlicer writes these)', async () => {
    const r = await parseFile(makeZip({ '3D/3dmodel.model': '<model/>', 'Metadata/slice_info.config': sliceInfo }, false, true));
    expect(r.totalWeightG).toBe(20.5);
    await expect(parseFile(makeZip({ '3D/3dmodel.model': '<model/>' }, true, true))).rejects.toThrow(/3D model/);
  });
  it('reads stored entries', async () => {
    const r = await parseFile(makeZip({ 'Metadata/slice_info.config': sliceInfo }, true));
    expect(r.totalWeightG).toBe(20.5);
  });
  it('falls back to plate gcode', async () => {
    const r = await parseFile(makeZip({ 'Metadata/plate_1.gcode': '; BambuStudio 01.09\n; filament used [g] = 9.5\n; total estimated time: 30m 0s\n' }));
    expect(r.totalWeightG).toBe(9.5);
    expect(r.printTimeSeconds).toBe(1800);
  });
  it('reads G-code inside an UltiMaker .ufp package', async () => {
    const r = await parseFile(makeZip({ '/3D/model.gcode': ';FLAVOR:Griffin\n;PRINT.TIME:600\n;EXTRUDER_TRAIN.0.MATERIAL.VOLUME_USED:1000\n;Generated with Cura_SteamEngine 5.7\n' }));
    expect(r.slicer).toBe('cura');
    expect(r.printTimeSeconds).toBe(600);
    expect(r.totalWeightG).toBe(1.24);
  });
  it('explains a plain model 3MF', async () => {
    // Entry layout of real plain models: 3MF Consortium core samples, OrcaSlicer calib/filament_flow, PrusaSlicer test_3mf.
    await expect(parseFile(makeZip({ '3D/3dmodel.model': '<model/>' }))).rejects.toThrow(/3D model, not a sliced file/);
    await expect(parseFile(makeZip({ '3D/3dmodel.model': '<model/>', 'Metadata/thumbnail.png': 'x' }))).rejects.toThrow(/3D model/);
  });
  it('explains an unsliced Bambu Studio / OrcaSlicer project', async () => {
    const unsliced = `<config><plate><metadata key="index" value="1"/></plate></config>`;
    for (const files of <Record<string, string>[]>[
      { '3D/3dmodel.model': '<model/>', 'Metadata/project_settings.config': '{}', 'Metadata/model_settings.config': '<config/>' },
      { '3D/3dmodel.model': '<model/>', 'Metadata/slice_info.config': unsliced },
    ]) {
      await expect(parseFile(makeZip(files))).rejects.toThrow(/hasn't been sliced.*Export plate sliced file/);
    }
  });
  it('explains a PrusaSlicer project', async () => {
    // Entry layout of real tests/data/seam_test_object.3mf from PrusaSlicer.
    const files = { '3D/3dmodel.model': '<model/>', 'Metadata/Slic3r_PE.config': '; x', 'Metadata/Slic3r_PE_model.config': '<config/>' };
    await expect(parseFile(makeZip(files))).rejects.toThrow(/PrusaSlicer project.*\.bgcode/);
  });
  it('explains a Cura project', async () => {
    const files = { '3D/3dmodel.model': '<model/>', 'Cura/creality_ender3.def.cfg': '[general]' };
    await expect(parseFile(makeZip(files))).rejects.toThrow(/Cura project/);
  });
  it('still parses a project saved after slicing', async () => {
    const r = await parseFile(makeZip({ 'Metadata/project_settings.config': '{}', 'Metadata/slice_info.config': sliceInfo }));
    expect(r.totalWeightG).toBe(20.5);
  });
  it('reports corrupt deflate data as a ParseError (found by fuzzing real files)', async () => {
    const z = makeZip({ 'Metadata/slice_info.config': sliceInfo });
    const start = 30 + 'Metadata/slice_info.config'.length; // first entry: local header + name, no extra field
    z.fill(0xff, start, start + 4); // deflate block type 3 is invalid
    await expect(parseFile(z)).rejects.toBeInstanceOf(ParseError);
  });
  it('rejects corrupt zips', async () => {
    await expect(parseFile(new Uint8Array([0x50, 0x4b, 1, 2, 3, 4]))).rejects.toThrow();
  });
});

/** Build a .bgcode file: header, then blocks of [type, compression, params, INI text]. */
function makeBgcode(blocks: [number, number, string][], checksum = 1): Uint8Array {
  const parts: Buffer[] = [Buffer.from('GCDE'), Buffer.alloc(6)];
  parts[1].writeUInt32LE(1, 0);
  parts[1].writeUInt16LE(checksum, 4);
  for (const [type, compression, text] of blocks) {
    const raw = Buffer.from(text);
    const data = compression === 1 ? deflateSync(raw) : raw;
    const h = Buffer.alloc(compression ? 12 : 8);
    h.writeUInt16LE(type, 0);
    h.writeUInt16LE(compression, 2);
    h.writeUInt32LE(raw.length, 4);
    if (compression) h.writeUInt32LE(data.length, 8);
    parts.push(h, Buffer.alloc(type === 5 ? 6 : 2), data, Buffer.alloc(checksum === 1 ? 4 : 0));
  }
  return new Uint8Array(Buffer.concat(parts));
}

describe('bgcode', () => {
  // Block layout mirrors a real PrusaSlicer 2.9 file: file, printer, thumbnail, print (deflate), slicer (deflate), gcode.
  const blocks: [number, number, string][] = [
    [0, 0, 'Producer=PrusaSlicer 2.9.0\n'],
    [3, 0, 'printer_model=MINI\nfilament_type=ABS\n'],
    [5, 0, 'PNGDATA'],
    [4, 1, 'filament used [mm]=24826.34\nfilament used [g]=62.10\ntotal filament used [g]=62.10\nestimated printing time (normal mode)=7h 25m 7s\n'],
    [2, 1, 'filament_density=1.04\nfilament_type=ABS\n'],
    [1, 3, 'heatshrink gcode is never read'],
  ];
  it('reads print metadata from a PrusaSlicer .bgcode', async () => {
    const r = await parseFile(makeBgcode(blocks));
    expect(r.slicer).toBe('prusa');
    expect(r.printTimeSeconds).toBe(7 * 3600 + 25 * 60 + 7);
    expect(r.totalWeightG).toBe(62.1);
    expect(r.filaments[0].type).toBe('ABS');
    expect(r.warnings).toEqual([]);
  });
  it('handles files without checksums', async () => {
    const r = await parseFile(makeBgcode(blocks, 0));
    expect(r.totalWeightG).toBe(62.1);
  });
  it('rejects truncated files', async () => {
    const b = makeBgcode(blocks);
    await expect(parseFile(b.subarray(0, 40))).rejects.toThrow(/Corrupt/);
  });
});

describe('zero-density profiles (written by an AI agent, Claude)', () => {
  // Header shape copied from a real OrcaSlicer 2.x file whose profile had filament_density = 0.
  const orcaZero = (extra = '') => `; HEADER_BLOCK_START\n; generated by OrcaSlicer 2.2.0 on 2025-01-01 at 10:00:00\n; total estimated time: 7m 12s\n; HEADER_BLOCK_END\nG1 X1\n; filament used [mm] = 239.42\n; filament used [cm3] = 0.58\n; total filament used [g] = 0.00\n; filament_density = 0\n${extra}`;

  it('estimates weight from cm3 with the type density, and warns', () => {
    const r = parseGcodeText(orcaZero('; filament_type = PETG\n'));
    expect(r.slicer).toBe('orca');
    expect(r.totalWeightG).toBeCloseTo(0.58 * 1.27, 2);
    expect(r.filaments[0].weightEstimated).toBe(true);
    expect(r.filaments[0]).not.toHaveProperty('volumeCm3');
    expect(r.warnings).toContain('Your slicer profile has no filament density, so weight is estimated.');
  });

  it('falls back to PLA density when the type is unknown, and to length without cm3', () => {
    expect(parseGcodeText(orcaZero('; filament_type = Weird\n')).totalWeightG).toBeCloseTo(0.58 * 1.24, 2);
    const noCm3 = orcaZero().replace('; filament used [cm3] = 0.58\n', '');
    const expected = (Math.PI * 0.875 ** 2 * 239.42 * 1.24) / 1000;
    expect(parseGcodeText(noCm3).totalWeightG).toBeCloseTo(expected, 2);
  });

  it('keeps a genuine 0 g for an unused extruder and real weights untouched', () => {
    const t = `; generated by PrusaSlicer 2.8.0\nG1 X1\n; filament used [mm] = 1000, 0\n; filament used [cm3] = 2.4, 0\n; filament used [g] = 3.01, 0\n; filament_density = 1.24, 1.24\n; estimated printing time (normal mode) = 10m\n`;
    const r = parseGcodeText(t);
    expect(r.totalWeightG).toBe(3.01);
    expect(r.filaments.every((f) => !f.weightEstimated)).toBe(true);
    expect(r.warnings.some((w) => /density/.test(w))).toBe(false);
  });
});

describe('printer model (hq t012; written by an AI agent, Claude)', () => {
  it('reads printer_model and printer_settings_id from PrusaSlicer/Orca config lines', () => {
    // Shapes copied from real files in docs/reference-data.md (PrusaSlicer 2.9 3DBenchy, OrcaSlicer 2.3 cubewithironing).
    const prusa = parseGcodeText('; generated by PrusaSlicer 2.9.2\n; printer_model = MINIIS\n; physical_printer_settings_id = \n; printer_settings_id = Original Prusa MINI & MINI+ Input Shaper - no purge line\n');
    expect(prusa.printerModel).toBe('MINIIS');
    expect(prusa.printerPreset).toBe('Original Prusa MINI & MINI+ Input Shaper - no purge line');
    const orca = parseGcodeText(';printer_model:Elegoo Centauri Carbon\n; generated by OrcaSlicer 2.3.1\n; printer_model = Elegoo Centauri Carbon\n');
    expect(orca.printerModel).toBe('Elegoo Centauri Carbon');
    expect(orca.printerPreset).toBeUndefined();
  });
  it('reads the Cura Griffin machine name, and nothing from plain Marlin Cura files', () => {
    expect(parseGcodeText(';FLAVOR:Griffin\n;TARGET_MACHINE.NAME:Ultimaker S5\n;PRINT.TIME:60\n').printerModel).toBe('Ultimaker S5');
    expect(parseGcodeText(';FLAVOR:Marlin\n;TIME:420\n;Filament used: 0.3m\n').printerModel).toBeUndefined();
  });
  it('cleans hostile values: control chars, quotes, length, empty', () => {
    const r = parseGcodeText(`; printer_model = "<img src=x onerror=alert(1)>\u0007‮${'A'.repeat(200)}"\n; printer_settings_id =    \n`);
    expect(r.printerModel).toMatch(/^<img src=x onerror=alert\(1\)> A+$/);
    expect(r.printerModel!.length).toBeLessThanOrEqual(64);
    expect(r.printerPreset).toBeUndefined();
  });
  it('reads the printer from a .bgcode printer block', async () => {
    const r = await parseFile(makeBgcode([[0, 0, 'Producer=PrusaSlicer 2.9.0\n'], [3, 0, 'printer_model=MINI\n'], [2, 1, 'printer_settings_id=Original Prusa MINI & MINI+\n'], [1, 3, 'x']]));
    expect(r.printerModel).toBe('MINI');
    expect(r.printerPreset).toBe('Original Prusa MINI & MINI+');
  });
  it('reads the printer from a Bambu/Orca 3MF project_settings.config, and ignores bad JSON', async () => {
    const info = '<config><plate><metadata key="prediction" value="843"/><filament id="1" type="PLA" used_m="1.2" used_g="3.69"/></plate></config>';
    const ok = await parseFile(makeZip({ 'Metadata/slice_info.config': info, 'Metadata/project_settings.config': '{"printer_model": "Bambu Lab H2C", "printer_settings_id": "Bambu Lab H2C 0.4 nozzle"}' }));
    expect(ok.printerModel).toBe('Bambu Lab H2C');
    expect(ok.printerPreset).toBe('Bambu Lab H2C 0.4 nozzle');
    for (const bad of ['not json', '{"printer_model": 5}', 'null', '[]']) {
      const r = await parseFile(makeZip({ 'Metadata/slice_info.config': info, 'Metadata/project_settings.config': bad }));
      expect(r.printerModel).toBeUndefined();
      expect(r.totalWeightG).toBe(3.69);
    }
  });
});
