// Plausibility warnings (hq t049). Written by an AI agent (Claude).
import { describe, expect, it } from 'vitest';
import { parseGcodeText } from './parsers/gcode';
import { parseFile } from './parsers/index';
import { implausibleTotals, impliedDensity } from './parsers/sanity';

const enc = (s: string) => new TextEncoder().encode(s);

describe('implausible totals', () => {
  it('passes real jobs: 3.74 g in 527 s (B01) and 1666.63 g in 77519 s (B06 slab)', () => {
    expect(implausibleTotals({ totalWeightG: 3.74, printTimeSeconds: 527 })).toEqual([]);
    expect(implausibleTotals({ totalWeightG: 1666.63, printTimeSeconds: 77519 })).toEqual([]);
  });
  it('flags grams per hour outside 0.5-200', () => {
    expect(implausibleTotals({ totalWeightG: 3024.82, printTimeSeconds: 1030 })[0]).toMatch(/^3025 g in 17 min is 10572 g per print hour/);
    expect(implausibleTotals({ totalWeightG: 0.2, printTimeSeconds: 7200 })[0]).toMatch(/0.1 g per print hour/);
  });
  it('flags a near-zero time for a real amount of filament, once', () => {
    const w = implausibleTotals({ totalWeightG: 12, printTimeSeconds: 5 });
    expect(w).toHaveLength(1);
    expect(w[0]).toMatch(/5 s for 12 g .* not plausible/);
    expect(implausibleTotals({ totalWeightG: 0.5, printTimeSeconds: 5 })).toEqual([]);
  });
  it('says nothing when weight or time is missing', () => {
    expect(implausibleTotals({ totalWeightG: undefined, printTimeSeconds: 5 })).toEqual([]);
    expect(implausibleTotals({ totalWeightG: 10, printTimeSeconds: undefined })).toEqual([]);
  });
  it('is added by parseFile for any format', async () => {
    const r = await parseFile(enc('; generated by PrusaSlicer 2.9.6\n; filament used [g] = 500\n; estimated printing time (normal mode) = 2m 0s\n'));
    expect(r.totalWeightG).toBe(500);
    expect(r.warnings.join(' ')).toMatch(/per print hour/);
  });
});

describe('implausible filament data in G-code', () => {
  // Real OrcaSlicer 2.4.2 cube (O01): 1214.13 mm, 2.92 cm³, 3.62 g, 1.75 mm, density 1.24.
  const orca = (g: string, cm3: string, dia = '1.75') =>
    `; generated by OrcaSlicer 2.4.2\n; filament used [mm] = 1214.13\n; filament used [cm3] = ${cm3}\n; filament used [g] = ${g}\n; estimated printing time (normal mode) = 17m 10s\n; filament_density = 1.24\n; filament_diameter = ${dia}\n`;
  it('real header lines give no warning', () => {
    expect(impliedDensity(3.62, 1214.13, 1.75)).toBeCloseTo(1.24, 2);
    expect(parseGcodeText(orca('3.62', '2.92')).warnings).toEqual([]);
  });
  it('flags weight that implies an impossible density, without changing it', () => {
    const r = parseGcodeText(orca('36.2', '2.92'));
    expect(r.totalWeightG).toBe(36.2);
    expect(r.warnings).toEqual([expect.stringMatching(/density of 12 g\/cm³.*Check the filament density \(and diameter\)/)]);
  });
  it('uses the stated diameter (2.85 mm filament is fine)', () => {
    const g = (1.24 * Math.PI * 1.425 ** 2 * 1214.13 / 1000).toFixed(2);
    expect(parseGcodeText(orca(g, (Math.PI * 1.425 ** 2 * 1214.13 / 1000).toFixed(2), '2.85')).warnings).toEqual([]);
  });
  it('flags mm³ written as cm³ when weight comes from volume', () => {
    // Density 0 profile: the slicer writes 0.00 g, so weight would come from the (wrong) volume.
    const r = parseGcodeText(orca('0.00', '2922.56').replace('filament_density = 1.24', 'filament_density = 0'));
    expect(r.warnings.join(' ')).toMatch(/volume doesn't match its filament length \(off by about 1001×/);
    expect(r.warnings.join(' ')).toMatch(/no filament density/);
  });
});
